-- Клиенты --------------------------------------------------

CREATE TABLE customers (
    customer_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_first_name varchar(64) NOT NULL,
    customer_last_name varchar(64) NOT NULL,
    customer_middle_name varchar(64) NOT NULL
);

INSERT INTO customers (customer_first_name, customer_last_name, customer_middle_name)
VALUES ('Вячеслав', 'Кудрявцев', 'Юрьевич');

-- Заказы --------------------------------------------------

CREATE TABLE orders (
    order_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id int REFERENCES customers(customer_id) NOT NULL,
    order_date date NOT NULL,
    order_time time NOT NULL
);

INSERT INTO orders (customer_id, order_date, order_time)
VALUES (1, '2023-07-19', '15:52');

-- Продукты --------------------------------------------------

CREATE TABLE products (
  product_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_name varchar(64) NOT NULL UNIQUE,
  product_description text,
  product_price int NOT NULL
);

-- Заказы и продукты --------------------------------------------------

CREATE TABLE orders_products (
    orders_products_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	order_id int REFERENCES orders(order_id),
    product_id int REFERENCES products(product_id)
);